stages:
  - deploy

deploy:
  stage: deploy
  tags:
    - shell
  script:
    - nvm use 18
    - rm -rf node_modules/
    - npm install
    - npm run migrate
    - npm start
  rules:
    - if: '$CI_COMMIT_BRANCH == "main"'
      exists:
        - .gitlab-ci.yml
    - when: never
